name: flutter_firebase_messaging_v8
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  cloud_firestore: ^0.16.0
  flutter_local_notifications: ^4.0.0
  get: ^3.23.1
  equatable: ^1.2.5
  dartz: ^0.9.2
  http: ^0.12.2
  path_provider: ^1.6.7
  rxdart: ^0.24.0
  sqflite: ^1.3.2+1
  flutter_slidable:
  sizer: ^1.1.8
  flutter_icons: ^1.1.0
  intl: ^0.16.1
  uuid: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: Kanit-Regular
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf